name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest TryHackMe image badge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Update to v3 for Node20 support

      - name: Update TryHackMe Badge
        uses: p4p1/tryhackme-badge-workflow@v2.0.1 # Updated version of this action
        with:
          THM_USERNAME: "SudoSesh" # Replace with your TryHackMe username

